# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.18.3, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.18.3
      uses: actions/setup-node@v1
      with:
        node-version: 12.18.3
    - run: npm ci
    - run: npm run build --if-present
    - run: npm i
    # - run: npm start
actions:
- action: "Push to https://git.heroku.com/calm-eyrie-56872.git"
  type: "PUSH"
  login: "aditya.gupta@hiteshi.com"
  password: "Aaditya#1234"
  push_tags: false
  git_auth_mode: "HTTP"
  target_branch: "Master"
  push_url: "https://git.heroku.com/calm-eyrie-56872.git"
  comment: "Trial"
  tag: "demoTag"
  deployment_excludes:
  - "/tmp/"
  trigger_condition: "ALWAYS"
  use_custom_gitignore: true
  without_force: false